### ISSUE TITLE
scripts/release without prior scripts/build generates error

### ISSUE THREAD

**Issue by jdeisenberg** [swannodette/mies#21]
Given a project created with `lein new mies m060`, attempting to make a release version via `scripts/release` without first making the dev version via `scripts/build` (probably not a good idea, of course) produces this:

````
[david@localhost m060]$ scripts/release
Building ...
Analyzing jar:file:/home/david/.m2/repository/org/clojure/clojurescript/0.0-2850/clojurescript-0.0-2850.jar!/cljs/core.cljs
Compiling src/m060/core.cljs
Analyzing jar:file:/home/david/.m2/repository/org/clojure/clojurescript/0.0-2850/clojurescript-0.0-2850.jar!/clojure/browser/repl.cljs
Analyzing jar:file:/home/david/.m2/repository/org/clojure/clojurescript/0.0-2850/clojurescript-0.0-2850.jar!/clojure/browser/net.cljs
Analyzing jar:file:/home/david/.m2/repository/org/clojure/clojurescript/0.0-2850/clojurescript-0.0-2850.jar!/clojure/browser/event.cljs
Analyzing jar:file:/home/david/.m2/repository/org/clojure/clojurescript/0.0-2850/clojurescript-0.0-2850.jar!/cljs/repl.cljs
Compiling release/clojure/browser/repl.cljs
Compiling release/clojure/browser/event.cljs
Compiling release/cljs/repl.cljs
Compiling release/clojure/browser/net.cljs
Compiling release/cljs/core.cljs
Exception in thread "main" java.io.FileNotFoundException: out/m060.js (No such file or directory), compiling:(/home/david/mtest/m060/scripts/release.clj:3:25)
        at clojure.lang.Compiler.load(Compiler.java:7142)
        at clojure.lang.Compiler.loadFile(Compiler.java:7086)
        at clojure.main$load_script.invoke(main.clj:274)
        at clojure.main$script_opt.invoke(main.clj:336)
        at clojure.main$main.doInvoke(main.clj:420)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at clojure.lang.Var.invoke(Var.java:379)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
        at clojure.lang.Reflector.invokeStaticMethod(Reflector.java:207)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
        at clojure.lang.Reflector.invokeStaticMethod(Reflector.java:207)
        at user$eval5.invoke(form-init7572786293818919277.clj:1)
        at clojure.lang.Compiler.eval(Compiler.java:6703)
        at clojure.lang.Compiler.eval(Compiler.java:6693)
        at clojure.lang.Compiler.load(Compiler.java:7130)
        at clojure.lang.Compiler.loadFile(Compiler.java:7086)
        at clojure.main$load_script.invoke(main.clj:274)
        at clojure.main$init_opt.invoke(main.clj:279)
        at clojure.main$initialize.invoke(main.clj:307)
        at clojure.main$null_opt.invoke(main.clj:342)
        at clojure.main$main.doInvoke(main.clj:420)
        at clojure.lang.RestFn.invoke(RestFn.java:421)
        at clojure.lang.Var.invoke(Var.java:383)
        at clojure.lang.AFn.applyToHelper(AFn.java:156)
        at clojure.lang.Var.applyTo(Var.java:700)
        at clojure.main.main(main.java:37)
[snip]
````

**Comment by jdeisenberg** [comment]
Appears fixed in pull request #23.
