### ISSUE TITLE
brepl fails to start correctly?

### ISSUE THREAD

**Issue by bcambel** [swannodette/mies#34]
```
clojure.lang.ExceptionInfo: Referred var cljs.pprint/pprint does not exist at line 1 <cljs repl> {:file "<cljs repl>", :line 1, :column 1, :tag :cljs/analysis-error}
	at clojure.core$ex_info.invoke(core.clj:4593)
	at cljs.analyzer$error.invoke(analyzer.cljc:384)
	at cljs.analyzer$error.invoke(analyzer.cljc:382)
	at cljs.analyzer$check_uses.invoke(analyzer.cljc:1300)
	at cljs.analyzer$fn__1640.invoke(analyzer.cljc:1547)
	at clojure.lang.MultiFn.invoke(MultiFn.java:251)
	at cljs.analyzer$analyze_seq.invoke(analyzer.cljc:1900)
	at cljs.analyzer$analyze$fn__1867.invoke(analyzer.cljc:1992)
	at cljs.analyzer$analyze.invoke(analyzer.cljc:1985)
	at cljs.repl$evaluate_form.invoke(repl.cljc:429)
	at cljs.repl$repl_STAR_$fn__3613.invoke(repl.cljc:800)
	at cljs.repl$repl_STAR_$fn__3621$fn__3622.invoke(repl.cljc:830)
	at cljs.repl$repl_STAR_$fn__3621.invoke(repl.cljc:827)
	at cljs.compiler$with_core_cljs.invoke(compiler.cljc:968)
	at cljs.repl$repl_STAR_.invoke(repl.cljc:824)
	at user$eval594.invoke(brepl.clj:12)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.load(Compiler.java:7227)
	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$script_opt.invoke(main.clj:337)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.lang.Var.invoke(Var.java:379)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeStaticMethod(Reflector.java:207)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
	at clojure.lang.Reflector.invokeStaticMethod(Reflector.java:207)
	at user$eval5.invoke(form-init6484620343865078537.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.eval(Compiler.java:6772)
	at clojure.lang.Compiler.load(Compiler.java:7227)
	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
To quit, type: :cljs/quit
cljs.user=>
```

**Comment by mneise** [comment]
@bcambel I could not reproduce this. Is this still an issue for you? Are you using the template as it is or have you maybe changed the ClojureScript version?

**Comment by bcambel** [comment]
I was using 0.0-3308 ( not exactly remember if I changed it or not ). I didn't get the exception with the latest version of Clojurescript ["1.7.48"]

**Comment by mneise** [comment]
This doesn't seem to be a problem anymore.

**Comment by mcdemarco** [comment]
I get this exception with the latest version of Clojurescript, with the dependency `[reagent "0.5.0"]`.

**Comment by mneise** [comment]
@mcdemarco Do you also get this exception when starting the repl right after creating a new project with this template without modifying anything or adding any additional dependencies?

**Comment by mcdemarco** [comment]
No.  I did notice that just adding the dependency with no code changes keeps the repl from starting up, although it doesn't throw the error in that case.

**Comment by mneise** [comment]
@mcdemarco This seems to be a dependency problem. Reagent `0.5.0` uses ClojureScript `0.0-2816`, which didn't have `pprint` support yet. Upgrading to the most recent version of reagent (`0.5.1-rc2`) or explicitly excluding ClojureScript when adding reagent as a dependency to your project should solve this problem, e.g. `[reagent "0.5.0" :exclusions [[org.clojure/clojurescript]]]`.
